apiVersion: v1
kind: Service
metadata:
  name: login-service
  namespace: microservices
spec:
  selector:
    app: login-microservice
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
