apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-app-argocd
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp
  
  syncPolicy:
    syncOptions:
    - CreateNamespace = true
    automated:
      selfHeal: true
      prune: true