apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dataset-argocd
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/haythem05/Deployments.git
    targetRevision: main
    path: Database
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp
  
  syncPolicy:
    syncOptions:
    - CreateNamespace = true
    automated:
      selfHeal: true
      prune: true